name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JS via node
        uses: actions/setup-node@v4
        with:
          node-version: 20 # LTS release
      - name: install jest
        run: npm init -y && npm install jest@latest --global
      - uses: education/autograding@v1